name: ace_ai_dart_sdk
description: Dart & Flutter SDK for AllCollegeEvent (HackGuru AI Intelligence Layer)
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.2.0

dev_dependencies:
  test: ^1.24.0
